### ISSUE TITLE
project.json missing

### ISSUE THREAD

**Issue by Ikarus76** [ms-iot/internetradio#14]
Hi,
just wanted to tell you, that the project.json file is missing for the "InternetRadioHeaded" project.

regards,
michael

**Comment by IoTGirl** [comment]
Hi Ben,
Would you be able to review this issue?
Sincerest thanks,
IoTGirl

**Comment by torstenmo** [comment]
Hi,
I had the same issue. You can just copy the project.json file from the project "InternetRadioHeadless" to the project "InternetRadioHeaded". This will fix all compile issues. In Addition the key file "InternetRadioController_TemporaryKey.pfx" is missing. This is needed for the digital signature of the .NET assembly of InternetRadioController.
Hope this helps.
@Ben: If it's OK for you, I could update the sources on github as well.
Regards,
Torsten

**Comment by IoTGirl** [comment]
@torstenmo and @bethoma Was  there a changelist made for this issue based on Torsten's comment above? Has it been addressed?

**Comment by IoTGirl** [comment]
Closing Stale - Please provide a change request if this needs to be updated in the GitHub.
