### ISSUE TITLE
Layout on player page is broken.

### ISSUE THREAD

**Issue by naikrovek** [ms-iot/internetradio#15]
![image](https://user-images.githubusercontent.com/284498/29829981-7e87077c-8ca6-11e7-9f09-003a3ccf5f10.png)

This page does not look like it is laid out correctly, at all.  I don't know enough about how this application works to fix it, but I wanted to flag it as an issue since it needs attention.

**Comment by saraclay** [comment]
Closing this out as it's been a while. Feel free to file an issue on ms-iot/content as we are more active there.
