### ISSUE TITLE
Touchscreen get unresponsive

### ISSUE THREAD

**Issue by ZeProgFactory** [ms-iot/internetradio#17]
When playing a stream for a few seconds the touchscreen got unresponsive. 
Stopping the stream or restarting of the app does not bring the touchscreen back. Only a restart of the PI reactivates it.

The user interface of the app remains responsive via the Windows IOT Remote Client.

I observed the same issue when using the MediaElement in another project. I'm wondering if there is some issue on I2C bus when playing sounds ...

Config: PIE 3 with official PI 7" Touchscreen.

**Comment by saraclay** [comment]
Closing this out as it's been a while. Feel free to file an issue on ms-iot/content as we are more active there.
