### ISSUE TITLE
Windows 10 IOT Issues

### ISSUE THREAD

**Issue by lankylad9** [ms-iot/internetradio#18]
Remove alert | Edit | Change type
Question
You cannot vote on your own post
0
I have downloaded the Windows 10 IOT internet radio sample from GIT and run the two extra commands that are required (git submodule init and git submodule update).

The IOT Dashboard is talking to my Raspberry Pi 3

The solution loads OK into Visual Studio 2017 Community.

When I try to Build the solution I get errors:

InternetRadioDevice\ARM\Debug\InternetRadioAllJoyn\com.microsoft.maker.InternetRadio.winmd cannot be found
com::microsoft::maker::InternetRadio::AllJoynMessageArgStructure::SetAt The parameter 'item' is named 'value' on the base function and must be matched in a published implementation
com::microsoft::maker::InternetRadio::AllJoynMessageArgStructure::InsertAt The parameter 'item' is named 'value' on the base function and must be matched in a published implementation
com::microsoft::maker::InternetRadio::AllJoynMessageArgStructure::Append The parameter 'item' is named 'value' on the base function and must be matched in a published implementation
com::microsoft::maker::InternetRadio::AllJoynMessageArgStructure::SReplaceAll The parameter 'arr' is named 'value' on the base function and must be matched in a published implementation

**Comment by gzhu1957** [comment]
@lankylad9 +1, we have the exact same issue. Missing the same file as you:` InternetRadio.winmd`

**Comment by saraclay** [comment]
Closing this out as it's been a while. Feel free to file an issue on ms-iot/content as we are more active there.
